metros = float(input('Digite uma distância em metros: '))
print('De acordo com o valor forneceido, as medidas são: ')

print(f'{metros / 1000}km')
print(f'{metros / 100}hm')
print(f'{metros / 10}dam')
print(f'{metros}m')
print(f'{metros * 10:.0f}dm')
print(f'{metros * 100:.0f}cm')
print(f'{metros * 1000:.0f}mm')
